export {
  DEFAULT_RESIDENCY_POLICY,
  MAX_MEMORY_BYTES,
  assertMemoryValue,
  createResidencyPolicy,
  estimatedMemory,
  isMemoryValue,
  isResidencyPolicy,
  measuredMemory,
  saturatingAddMemoryBytes,
  unavailableMemory,
  type AdmissionReason,
  type EstimatedMemoryBasis,
  type LoadAdmissionDecision,
  type LoadAdmissionTelemetry,
  type LoadReservation,
  type LoadReservationState,
  type MeasuredMemoryBasis,
  type MemoryValue,
  type ResidencyModelDescriptor,
  type ResidencyPolicy,
  type ResidentModelSnapshot,
  type UnavailableMemoryBasis,
} from "./types";
export {
  INSUFFICIENT_MODEL_MEMORY_CODE,
  InsufficientModelMemoryError,
  type InsufficientModelMemoryDetails,
} from "./errors";
