export {
  DEFAULT_RESIDENCY_POLICY,
  MAX_MEMORY_BYTES,
  assertMemoryValue,
  createResidencyPolicy,
  estimatedMemory,
  isMemoryValue,
  isResidencyPolicy,
  measuredMemory,
  saturatingAddMemoryBytes,
  unavailableMemory,
  type AdmissionReason,
  type EstimatedMemoryBasis,
  type LoadAdmissionDecision,
  type LoadAdmissionTelemetry,
  type LoadReservation,
  type LoadReservationState,
  type MeasuredMemoryBasis,
  type MemoryValue,
  type ResidencyModelDescriptor,
  type ResidencyPolicy,
  type ResidentModelSnapshot,
  type UnavailableMemoryBasis,
} from "./types";
export {
  INSUFFICIENT_MODEL_MEMORY_CODE,
  InsufficientModelMemoryError,
  type InsufficientModelMemoryDetails,
} from "./errors";
export {
  CONSERVATIVE_KV_BYTES_PER_TOKEN,
  DEFAULT_CONTEXT_TOKENS,
  DEFAULT_UNKNOWN_MODEL_MIN_BYTES,
  GIB,
  MIB,
  ModelLoadEstimateHistory,
  UNKNOWN_MODEL_MIN_BYTES_ENV,
  estimateModelLoadMemory,
  modelLoadEstimateHistoryKey,
  type ModelLoadEstimateOptions,
} from "./estimates";
export {
  compareIdleEvictionVictims,
  selectIdleEvictionVictims,
  type IdleEvictionSelectionOptions,
} from "./eviction";
export {
  DEFAULT_OS_HEADROOM_BYTES,
  DEFAULT_RUNTIME_HEADROOM_BYTES,
  OS_HEADROOM_BYTES_ENV,
  RUNTIME_HEADROOM_BYTES_ENV,
  ResidencyCoordinator,
  measuredResidencyMemory,
  type ResidencyCoordinatorDependencies,
  type ResidencyLifecycleAdapter,
  type ResidencyLoadOperation,
  type ResidencyLoadResult,
  type ResidencyMemorySnapshot,
} from "./coordinator";
