#!/usr/bin/env bun
// Builds apps/web with Vite and embeds the output into
// packages/server/src/web-assets.generated.ts so the dashboard ships inside
// the compiled clap binary with no extra files.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const webDir = join(root, "apps", "web");
const distDir = join(webDir, "dist");
const outFile = join(root, "packages", "server", "src", "web-assets.generated.ts");

const build = Bun.spawn(["bun", "run", "build"], {
  cwd: webDir,
  stdout: "inherit",
  stderr: "inherit",
});
if (await build.exited !== 0) process.exit(1);

const types: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".json": "application/json",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
};

async function collect(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...await collect(full));
    else files.push(full);
  }
  return files;
}

const files = (await collect(distDir)).filter((file) => !file.endsWith(".map"));
const assets: Record<string, { type: string; base64: string }> = {};
let total = 0;
for (const file of files.sort()) {
  const path = relative(distDir, file);
  const bytes = await readFile(file);
  total += bytes.byteLength;
  const extension = path.slice(path.lastIndexOf("."));
  assets[path] = { type: types[extension] ?? "application/octet-stream", base64: bytes.toString("base64") };
}

const banner = "// Generated by scripts/build-web.ts — do not edit by hand.\n// Run: bun run build:web\n";
await writeFile(outFile, `${banner}export const assets: Record<string, { type: string; base64: string }> = ${JSON.stringify(assets)};\n`);
console.log(`embedded ${files.length} files (${(total / 1024).toFixed(0)} KiB) into ${relative(root, outFile)}`);
