#!/usr/bin/env bun
// The CLI statically imports build outputs as embedded assets: libexec worker
// binaries, and the dashboard bundle generated by scripts/build-web.ts. Both
// are gitignored, so fresh checkouts (CI, new clones) have neither, which
// breaks module resolution for typecheck and every test that loads the CLI.
// Create placeholders for whatever is missing; a real build overwrites them,
// and extraction skips empty worker files at runtime.
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const libexec = join(root, "libexec");
await mkdir(libexec, { recursive: true });

for (const name of ["clap-llama", "clap-mlx", "mlx.metallib"]) {
  const path = join(libexec, name);
  if (!existsSync(path)) {
    await writeFile(path, "");
    console.log(`created placeholder ${path}`);
  }
}

// An empty asset map is the honest placeholder: the server already treats a
// missing asset as "not found", so a placeholder build serves no dashboard
// rather than pretending to have one.
const webAssets = join(root, "packages", "server", "src", "web-assets.generated.ts");
if (!existsSync(webAssets)) {
  await mkdir(dirname(webAssets), { recursive: true });
  await writeFile(webAssets,
    "// Placeholder created by scripts/ensure-libexec.ts because no web build\n"
    + "// was present. Run: bun run build:web\n"
    + "export const assets: Record<string, { type: string; base64: string }> = {};\n");
  console.log(`created placeholder ${webAssets}`);
}
